# 共用配置
DEBUG = True
DEBUG_TB_INTERCEPT_REDIRECTS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf8mb4"
SECRET_KEY = "123456"
AUTH_COOKIE_NAME = "movie_cat"
SCHEDULER_TIMEZONE = "Asia/Shanghai"
