# 共用配置
DEBUG = False
DEBUG_TB_INTERCEPT_REDIRECTS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf8mb4"
SECRET_KEY = "123456"
AUTH_COOKIE_NAME = "DNR"
SCHEDULER_TIMEZONE = "Asia/Shanghai"
